<?php

namespace App\Http\Requests\Admin\Post;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Validation\Rule;

class PostUpdateRequest extends PostRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array|string>
     */
    public function rules(): array
    {
        $rules = parent::rules();
        $rules += [
            'title' => ['required','string',Rule::unique('posts')->ignore($this->post->id)],
            'preview_image' => ['nullable','file','image'],
            'main_image' => ['nullable','file','image'],
        ];
        return $rules;

    }
    public function messages()
    {
        $messages = parent::messages(); // TODO: Change the autogenerated stub
        $messages += [
            'content.required' => 'This field is required.',
            'content.string' => 'Data must be of string type',
            'preview_image.file' => 'You must select a file',
            'main_image.file' => 'You must select a file',
            'preview_image.image' => 'You must select a image',
            'main_image.image' => 'You must select a image',
            'preview_image' => 'This field is required.',
            'main_image' => 'This field is required.',
        ];
        return $messages;
    }
}
